services:
  app: 
    build: .
    container_name: artia-app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    container_name: artia-database
    image: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes: 
      - ./data/pg:/data/postgres

