services:
  app: 
    build: ./back
    container_name: artia-app
    ports:
      - 3333:3333
    depends_on:
      - postgres
    volumes:
      - ./back:/app

  postgres:
    container_name: artia-database
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes: 
      - ./back/data/pg:/data/postgres

